{% set version = '0.1.0' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-pnwcolors
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PNWColors_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PNWColors/PNWColors_{{ version }}.tar.gz
  sha256: d2db440b2280bcd69ae931161fbd5abf473227cb5e73a3d1762cba4999a517de

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('PNWColors')"           # [not win]
    - "\"%R%\" -e \"library('PNWColors')\""  # [win]

about:
  home: https://github.com/jakelawlor/PNWColors
  license: CC0-1.0
  summary: PNW-Inspired Palettes for 'R' data visualizations. Palettes are variable in length
    and checked for colorblind accessibility from hue, saturation, and lightness value
    scaling using the 'Chroma.js  Color Palette Helper' <https://gka.github.io/palettes/>.
  license_family: CC
  license_file:
    - LICENSE-CC0

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: PNWColors
# Type: Package
# Title: Color Palettes Inspired by Nature in the US Pacific Northwest
# Version: 0.1.0
# Author: Jake Lawlor
# Maintainer: Jake Lawlor <jakealawlor@gmail.com>
# Description: PNW-Inspired Palettes for 'R' data visualizations. Palettes are variable in length and checked for colorblind accessibility from hue, saturation, and lightness value scaling using the 'Chroma.js  Color Palette Helper' <https://gka.github.io/palettes/>.
# Encoding: UTF-8
# LazyData: true
# License: CC0
# RoxygenNote: 7.0.2
# Suggests: ggplot2
# URL: https://github.com/jakelawlor/PNWColors
# NeedsCompilation: no
# Packaged: 2020-06-08 15:42:47 UTC; jakethesnake85
# Repository: CRAN
# Date/Publication: 2020-06-12 10:40:02 UTC
